/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            type: 'landing' | 'about' | 'contact' | 'specific';
            landingFields?: {
              mainTitle: string;
              highlightedTitle: string;
              subText: string;
              badge?: {
                text?: string | null;
                icon?: (string | null) | Media;
              };
              buttons?: {
                contactText?: string | null;
                servicesText?: string | null;
              };
              cards?:
                | {
                    label: string;
                    image: string | Media;
                    id?: string | null;
                  }[]
                | null;
              logosImage?: (string | null) | Media;
            };
            aboutFields?: {
              badge?: {
                text?: string | null;
                icon?: (string | null) | Media;
              };
              heading?: string | null;
              subHeading?: string | null;
              additionalText?: string | null;
              description?: string | null;
              video?: (string | null) | Media;
            };
            contactFields?: {
              titlePart1?: string | null;
              titlePart2?: string | null;
              highlightedWord?: string | null;
              description?: string | null;
              introText?: string | null;
              founderQuote?: string | null;
              founderName?: string | null;
              founderRole?: string | null;
              founderImage?: (string | null) | Media;
              images?: {
                image1?: (string | null) | Media;
                image2?: (string | null) | Media;
                image3?: (string | null) | Media;
                image4?: (string | null) | Media;
              };
            };
            specificFields?: {
              badge?: {
                text?: string | null;
                icon?: (string | null) | Media;
              };
              mainTitle?: string | null;
              highlightedWord?: string | null;
              subText?: string | null;
              description?: string | null;
              mainImage?: (string | null) | Media;
              stat1?: {
                value?: string | null;
                description?: string | null;
              };
              stat2?: {
                value?: string | null;
                description?: string | null;
              };
            };
            customTitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            highlightedWord?: string | null;
            subtitle?: string | null;
            variant?: ('landing' | 'about') | null;
            categories?:
              | {
                  id: 'academic' | 'beyond' | 'safety' | 'why';
                  label: string;
                  questions?:
                    | {
                        question: string;
                        answer: string;
                        id?: string | null;
                      }[]
                    | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            subtitle?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            subTags?:
              | {
                  tag: string;
                  id?: string | null;
                }[]
              | null;
            steps?:
              | {
                  title: string;
                  description: string;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methods';
          }
        | {
            subtitle?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            formTitle?: string | null;
            steps?:
              | {
                  stepNumber: string;
                  title: string;
                  description: string;
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'enquiry';
          }
        | {
            subtitle?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            metrics?:
              | {
                  metric: string;
                  description: string;
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trusted';
          }
        | {
            subtitle?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            partnersList?:
              | {
                  title: string;
                  description: string;
                  image: string | Media;
                  backgroundColor?: string | null;
                  borderColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners';
          }
        | {
            subtitle?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            cards?:
              | {
                  title: string;
                  text: string;
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            bottomTagline?: {
              text1?: string | null;
              highlightedTag?: string | null;
              text2?: string | null;
              outlinedTag?: string | null;
              text3?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            title?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'curriculum';
          }
        | {
            subtitle?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            features?:
              | {
                  tag?: string | null;
                  title: string;
                  quote: string;
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            caseStudy: {
              title: string;
              image: string | Media;
            };
            impact: {
              value: string;
              label?: string | null;
              image: string | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            founder: {
              quote?: string | null;
              name?: string | null;
              title?: string | null;
              image: string | Media;
            };
            values?:
              | {
                  icon: 'shield' | 'lightbulb' | 'users' | 'trophy';
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'coreValues';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            cards?:
              | {
                  headerImage: string | Media;
                  contentType?: ('text' | 'image') | null;
                  textValue?: string | null;
                  imageValue?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSupport';
          }
        | {
            title?: string | null;
            partners?:
              | {
                  logo: string | Media;
                  alt: string;
                  /**
                   * e.g. "w-full md:w-[206.8px]" for larger logos
                   */
                  customClass?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustedBy';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            mission: {
              label?: string | null;
              statement?: string | null;
              image1: string | Media;
              image2: string | Media;
              image3: string | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ourStory';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            valuesList?:
              | {
                  icon: string | Media;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutValues';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            team?:
              | {
                  name: string;
                  role: string;
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadership';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            virtualTab: {
              label?: string | null;
              title?: string | null;
              description?: string | null;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              image: string | Media;
            };
            tutoringTab: {
              label?: string | null;
              title?: string | null;
              description?: string | null;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              image: string | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'specificSolutions';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            description?: string | null;
            tabs?:
              | {
                  label: string;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'specificNeedHelp';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            highlightedWord?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'specificWayWeWork';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              type?: T;
              landingFields?:
                | T
                | {
                    mainTitle?: T;
                    highlightedTitle?: T;
                    subText?: T;
                    badge?:
                      | T
                      | {
                          text?: T;
                          icon?: T;
                        };
                    buttons?:
                      | T
                      | {
                          contactText?: T;
                          servicesText?: T;
                        };
                    cards?:
                      | T
                      | {
                          label?: T;
                          image?: T;
                          id?: T;
                        };
                    logosImage?: T;
                  };
              aboutFields?:
                | T
                | {
                    badge?:
                      | T
                      | {
                          text?: T;
                          icon?: T;
                        };
                    heading?: T;
                    subHeading?: T;
                    additionalText?: T;
                    description?: T;
                    video?: T;
                  };
              contactFields?:
                | T
                | {
                    titlePart1?: T;
                    titlePart2?: T;
                    highlightedWord?: T;
                    description?: T;
                    introText?: T;
                    founderQuote?: T;
                    founderName?: T;
                    founderRole?: T;
                    founderImage?: T;
                    images?:
                      | T
                      | {
                          image1?: T;
                          image2?: T;
                          image3?: T;
                          image4?: T;
                        };
                  };
              specificFields?:
                | T
                | {
                    badge?:
                      | T
                      | {
                          text?: T;
                          icon?: T;
                        };
                    mainTitle?: T;
                    highlightedWord?: T;
                    subText?: T;
                    description?: T;
                    mainImage?: T;
                    stat1?:
                      | T
                      | {
                          value?: T;
                          description?: T;
                        };
                    stat2?:
                      | T
                      | {
                          value?: T;
                          description?: T;
                        };
                  };
              customTitle?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              highlightedWord?: T;
              subtitle?: T;
              variant?: T;
              categories?:
                | T
                | {
                    id?: T;
                    label?: T;
                    questions?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        methods?:
          | T
          | {
              subtitle?: T;
              title?: T;
              highlightedWord?: T;
              subTags?:
                | T
                | {
                    tag?: T;
                    id?: T;
                  };
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        enquiry?:
          | T
          | {
              subtitle?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              formTitle?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trusted?:
          | T
          | {
              subtitle?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              metrics?:
                | T
                | {
                    metric?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              subtitle?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              partnersList?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    backgroundColor?: T;
                    borderColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              subtitle?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    image?: T;
                    id?: T;
                  };
              bottomTagline?:
                | T
                | {
                    text1?: T;
                    highlightedTag?: T;
                    text2?: T;
                    outlinedTag?: T;
                    text3?: T;
                  };
              id?: T;
              blockName?: T;
            };
        curriculum?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              subtitle?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              features?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    quote?: T;
                    image?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              caseStudy?:
                | T
                | {
                    title?: T;
                    image?: T;
                  };
              impact?:
                | T
                | {
                    value?: T;
                    label?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        coreValues?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              founder?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    title?: T;
                    image?: T;
                  };
              values?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactSupport?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              cards?:
                | T
                | {
                    headerImage?: T;
                    contentType?: T;
                    textValue?: T;
                    imageValue?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        trustedBy?:
          | T
          | {
              title?: T;
              partners?:
                | T
                | {
                    logo?: T;
                    alt?: T;
                    customClass?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ourStory?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              mission?:
                | T
                | {
                    label?: T;
                    statement?: T;
                    image1?: T;
                    image2?: T;
                    image3?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutValues?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              valuesList?:
                | T
                | {
                    icon?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        leadership?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              team?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specificSolutions?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              virtualTab?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    image?: T;
                  };
              tutoringTab?:
                | T
                | {
                    label?: T;
                    title?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specificNeedHelp?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              description?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specificWayWeWork?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlightedWord?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}